language: ruby
cache: bundler
addons:
  apt:
    packages:
      - libqtwebkit-dev
rvm:
 - 2.5
branches:
 only:
  - master
  - stable
before_install:
 - sudo service mysql restart
install:
 - gem install bundler:1.17.3
 - bundle install --path vendor/bundle
before_script:
 - bundle exec rake db:create
 - bundle exec rake db:setup
 - bundle exec rake db:migrate
 - bundle exec rake geo:fetch
script:
 - bundle --deployment
 - bundle exec brakeman
 - bundle exec rake ci --trace
